#æ·±åº¦åšå®¢ï¼šhttps://www.yfriend.xyz

port: 7890

socks-port: 7891

allow-lan: false

mode: Rule

log-level: silent

external-controller: 127.0.0.1:9090

dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
   - 119.29.29.29
   - 223.5.5.5


proxies:
- name: ğŸµ YFè§£é”èŠ‚ç‚¹
  type: http
  server: unblockmusic.yjs2635.xyz
  port: 60999
  
  - name: ğŸµ desè§£é”èŠ‚ç‚¹
    type: ss
    server: music.desperadoj.com
    port: 30001
    cipher: aes-128-gcm
    password: desperadoj.com_free_proxy_x80j
    
  - name: ğŸµ lolicoè§£é”èŠ‚ç‚¹
    server: music.lolico.me
    port: 39000
    type: http
    username: ""
    password: ""
    tls: false
    
   - name: ğŸ¶ è‡ªå·±è§£é”èŠ‚ç‚¹ ( Windows, Android )
    type: http
    server: 155.94.134.95
    port: 8848
    
  - name: ğŸ¶ è‡ªå·±è§£é” ( macOS, iOS, Linux )
    type: http
    server: 155.94.134.95
    port: 8848
    
       
  - name: ğŸµ æœªçŸ¥è§£é”èŠ‚ç‚¹
    server: taron.top
    port: 100
    type: http
    username: ""
    password: ""
    tls: false


proxy-groups:
- name: "Netease Music"
  type: select
  proxies: 
    - ğŸµ YFè§£é”èŠ‚ç‚¹
    - ğŸµ desè§£é”èŠ‚ç‚¹
    - ğŸµ lolicoè§£é”èŠ‚ç‚¹
    - ğŸ¶ è‡ªå·±è§£é”èŠ‚ç‚¹ ( Windows, Android )
    - ğŸ¶ è‡ªå·±è§£é” ( macOS, iOS, Linux )
    - ğŸµ æœªçŸ¥è§£é”èŠ‚ç‚¹
    - DIRECT

rules:
# Unblock Netease Music
- DOMAIN,api.iplay.163.com,Netease Music
- DOMAIN,apm3.music.163.com,Netease Music
- DOMAIN,apm.music.163.com,Netease Music
- DOMAIN,interface3.music.163.com,Netease Music
- DOMAIN,interface.music.163.com,Netease Music
- DOMAIN,music.163.com,Netease Music

#- DOMAIN,httpdns.n.netease.com,REJECT
- DOMAIN-SUFFIX,163yun.com,Netease Music
- DOMAIN,music.126.net,Netease Music
- DOMAIN-SUFFIX,mam.netease.com,Netease Music
- DOMAIN-SUFFIX,hz.netease.com,Netease Music

# CIDRè§„åˆ™
- IP-CIDR,39.105.63.80/32,Netease Music
- IP-CIDR,45.254.48.1/32,Netease Music
- IP-CIDR,47.100.127.239/32,Netease Music
- IP-CIDR,59.111.160.195/32,Netease Music
- IP-CIDR,59.111.160.197/32,Netease Music
- IP-CIDR,59.111.181.35/32,Netease Music
- IP-CIDR,59.111.181.38/32,Netease Music
- IP-CIDR,59.111.181.60/32,Netease Music
- IP-CIDR,101.71.154.241/32,Netease Music
- IP-CIDR,103.126.92.132/32,Netease Music
- IP-CIDR,103.126.92.133/32,Netease Music
- IP-CIDR,112.13.119.17/32,Netease Music
- IP-CIDR,112.13.122.1/32,Netease Music
- IP-CIDR,115.236.118.33/32,Netease Music
- IP-CIDR,115.236.121.1/32,Netease Music
- IP-CIDR,118.24.63.156/32,Netease Music
- IP-CIDR,193.112.159.225/32,Netease Music
- IP-CIDR,223.252.199.66/32,Netease Music
- IP-CIDR,223.252.199.67/32,Netease Music

- IP-CIDR,59.111.21.14/31,Netease Music
- IP-CIDR,59.111.179.214/32,Netease Music
- IP-CIDR,59.111.238.29/32,Netease Music

# Advertising
- DOMAIN,admusicpic.music.126.net,REJECT
- DOMAIN,iadmat.nosdn.127.net,REJECT
- DOMAIN,iadmusicmat.music.126.net,REJECT
- DOMAIN,iadmusicmatvideo.music.126.net,REJECT

# Final
- MATCH,DIRECT